[project]
name = "lenute"
version = "0.1.0"
description = "My library for building"
readme = "README.md"
requires-python = ">=3.13"

dependencies = ["jinja2>=3.1.6"]

[project.scripts]
lenute-cli = "lenute.commands.cli:main"
